// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: book_management.proto

package protos

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// BookManagementClient is the client API for BookManagement service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BookManagementClient interface {
	AddBook(ctx context.Context, in *Book, opts ...grpc.CallOption) (*wrapperspb.StringValue, error)
	DeleteBook(ctx context.Context, in *wrapperspb.StringValue, opts ...grpc.CallOption) (*Book, error)
	GetBook(ctx context.Context, in *wrapperspb.StringValue, opts ...grpc.CallOption) (*Book, error)
}

type bookManagementClient struct {
	cc grpc.ClientConnInterface
}

func NewBookManagementClient(cc grpc.ClientConnInterface) BookManagementClient {
	return &bookManagementClient{cc}
}

func (c *bookManagementClient) AddBook(ctx context.Context, in *Book, opts ...grpc.CallOption) (*wrapperspb.StringValue, error) {
	out := new(wrapperspb.StringValue)
	err := c.cc.Invoke(ctx, "/bookstore.BookManagement/addBook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookManagementClient) DeleteBook(ctx context.Context, in *wrapperspb.StringValue, opts ...grpc.CallOption) (*Book, error) {
	out := new(Book)
	err := c.cc.Invoke(ctx, "/bookstore.BookManagement/deleteBook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookManagementClient) GetBook(ctx context.Context, in *wrapperspb.StringValue, opts ...grpc.CallOption) (*Book, error) {
	out := new(Book)
	err := c.cc.Invoke(ctx, "/bookstore.BookManagement/getBook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BookManagementServer is the server API for BookManagement service.
// All implementations must embed UnimplementedBookManagementServer
// for forward compatibility
type BookManagementServer interface {
	AddBook(context.Context, *Book) (*wrapperspb.StringValue, error)
	DeleteBook(context.Context, *wrapperspb.StringValue) (*Book, error)
	GetBook(context.Context, *wrapperspb.StringValue) (*Book, error)
	mustEmbedUnimplementedBookManagementServer()
}

// UnimplementedBookManagementServer must be embedded to have forward compatible implementations.
type UnimplementedBookManagementServer struct {
}

func (UnimplementedBookManagementServer) AddBook(context.Context, *Book) (*wrapperspb.StringValue, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddBook not implemented")
}
func (UnimplementedBookManagementServer) DeleteBook(context.Context, *wrapperspb.StringValue) (*Book, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteBook not implemented")
}
func (UnimplementedBookManagementServer) GetBook(context.Context, *wrapperspb.StringValue) (*Book, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBook not implemented")
}
func (UnimplementedBookManagementServer) mustEmbedUnimplementedBookManagementServer() {}

// UnsafeBookManagementServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BookManagementServer will
// result in compilation errors.
type UnsafeBookManagementServer interface {
	mustEmbedUnimplementedBookManagementServer()
}

func RegisterBookManagementServer(s grpc.ServiceRegistrar, srv BookManagementServer) {
	s.RegisterService(&BookManagement_ServiceDesc, srv)
}

func _BookManagement_AddBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Book)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookManagementServer).AddBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bookstore.BookManagement/addBook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookManagementServer).AddBook(ctx, req.(*Book))
	}
	return interceptor(ctx, in, info, handler)
}

func _BookManagement_DeleteBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(wrapperspb.StringValue)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookManagementServer).DeleteBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bookstore.BookManagement/deleteBook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookManagementServer).DeleteBook(ctx, req.(*wrapperspb.StringValue))
	}
	return interceptor(ctx, in, info, handler)
}

func _BookManagement_GetBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(wrapperspb.StringValue)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookManagementServer).GetBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bookstore.BookManagement/getBook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookManagementServer).GetBook(ctx, req.(*wrapperspb.StringValue))
	}
	return interceptor(ctx, in, info, handler)
}

// BookManagement_ServiceDesc is the grpc.ServiceDesc for BookManagement service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BookManagement_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bookstore.BookManagement",
	HandlerType: (*BookManagementServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "addBook",
			Handler:    _BookManagement_AddBook_Handler,
		},
		{
			MethodName: "deleteBook",
			Handler:    _BookManagement_DeleteBook_Handler,
		},
		{
			MethodName: "getBook",
			Handler:    _BookManagement_GetBook_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "book_management.proto",
}
